check binay existence

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -16,7 +16,7 @@ jobs:
         run: /tmp/coding-style.sh . .
 
       - name: display cod report
-        run: cat coding-style-reports.log
+        run: cat coding-style-reports .log
 
       - name: report cod result
         run: |
@@ -29,3 +29,22 @@ jobs:
               fi
                   echo "Everything is good ! Keep on coding !"
                   exit 0
+
+  compilation:
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Checkout GH repository
+        uses: actions/checkout@master
+
+      - name: Compile repo
+        run: make
+
+      - name: Check binary existence
+        run: |
+        if [ ! -f ./swapupcase ] ; then
+          echo "Binary not found"
+          exit 1
+        fi
+        echo "Binary found"
+        exit 0
